on:
  push:
      branches: #your branch name

name: Build and publish package

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Run build.sh
        working-directory: ./build
        env:
          GIT_SHA: ${{ github.sha }}
        run: |
          chmod +x ./build.sh
          ./build.sh

  deploy:
      needs: build
      name: Deploy
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ap-southeast-2

        - name: Extract branch name
          shell: bash
          run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          id: extract_branch
          
        - name: Run deploy.sh
          working-directory: ./build
          env:
            GIT_SHA: ${{ github.sha }}
            BRANCH: ${{ steps.extract_branch.outputs.branch }}
          run: |
            chmod +x ./deploy.sh
            ./deploy.sh